### ISSUE TITLE
Update to commons-vfs 2.2

### ISSUE THREAD

**Issue by hmhagberg** [abashev/vfs-s3#45]
Commons-vfs 2.2 was released on 2017-10-06. Are there plans to update the custom version used by vfs-s3 to 2.2? Additionally, what exactly is the issue that necessitates a custom version (README only says "some concurrency issues")?

**Comment by abashev** [comment]
Yes, right now I'm working on version 3.0 - it will get updated commons-vfs and will be hosted at Maven Central (need to change group id to be in correct namespace)
I have to patch commons-vfs because it has a global lock on any filesystem activities and it is not good for S3 with stateless interaction in high-load environment.

**Comment by svella** [comment]
@abashev I've been sitting on a largish patch I created about 6 months ago that fixes truckloads of concurrency issues and completely reworks the changes you made to commons-vfs because they badly break concurrency for all the standard vfs providers. I also did it in a way so that it  could work safely with the standard vfs2 as well, though admittedly with significantly reduced performance. I guess now would be a good time to submit a pull request, but the main reason I've never gotten around to it is I just haven't had time to do the write up needed to explain the changes and why they are needed. I'll try to get on that soon but I really have been swamped with other things so I can't really promise anything.

**Comment by ptahchiev** [comment]
+1

**Comment by ptahchiev** [comment]
Any updates on this?

**Comment by abashev** [comment]
@ptahchiev I submitted changes to this branch https://github.com/abashev/vfs-s3/tree/branch-3.0.x but don't release it yet. I want to publish a new version to Maven Central but it requires some paperwork and rearranging group names and artifact id. But right now I don't have time for that.
